export const LANGUAGES = [
  { value: "af", label: "Afrikaans" },
  { value: "ar", label: "العربية" },
  { value: "cs", label: "Čeština" },
  { value: "da", label: "Dansk" },
  { value: "de", label: "Deutsch" },
  { value: "el", label: "Ελληνικά" },
  { value: "en", label: "English" },
  { value: "en-gb", label: "English (UK)" },
  { value: "es", label: "Español (España)" },
  { value: "es-la", label: "Español" },
  { value: "fa", label: "فارسی" },
  { value: "fi", label: "Suomi" },
  { value: "fr", label: "Français" },
  { value: "he", label: "עברית" },
  { value: "id", label: "Bahasa Indonesia" },
  { value: "it", label: "Italiano" },
  { value: "ja", label: "日本語" },
  { value: "ko", label: "한국어" },
  { value: "ms", label: "Bahasa Melayu" },
  { value: "nb", label: "Norsk" },
  { value: "nl", label: "Nederlands" },
  { value: "pl", label: "Polski" },
  { value: "pt-br", label: "Português (Brasil)" },
  { value: "pt", label: "Português (Portugal)" },
  { value: "ru", label: "Русский" },
  { value: "sv", label: "Svenska" },
  { value: "th", label: "ภาษาไทย" },
  { value: "tl", label: "Filipino" },
  { value: "tr", label: "Türkçe" },
  { value: "zh-cn", label: "中文(简体)" },
  { value: "zh-tw", label: "中文(台灣)" },
  { value: "bn", label: "বাংলা" },
  { value: "gu", label: "ગુજરાતી" },
  { value: "hi", label: "हिन्दी" },
  { value: "hr", label: "Hrvatski" },
  { value: "hu", label: "Magyar" },
  { value: "kn", label: "ಕನ್ನಡ" },
  { value: "ml", label: "മലയാളം" },
  { value: "mr", label: "मराठी" },
  { value: "ne", label: "नेपाली" },
  { value: "pa", label: "ਪੰਜਾਬੀ" },
  { value: "si", label: "සිංහල" },
  { value: "sk", label: "Slovenčina" },
  { value: "ta", label: "தமிழ்" },
  { value: "te", label: "తెలుగు" },
  { value: "ur", label: "اردو" },
  { value: "vi", label: "Tiếng Việt" },
  { value: "zh-hk", label: "中文(香港)" },
  { value: "bg", label: "Български" },
  { value: "fr-ca", label: "Français (Canada)" },
  { value: "ro", label: "Română" },
  { value: "sr", label: "Српски" },
  { value: "uk", label: "Українська" },
];
